CREATE TABLE IF NOT EXISTS project_tools (
 project_id VARCHAR(64) NOT NULL,
 section VARCHAR(32) NOT NULL,
 entries JSON NOT NULL,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 PRIMARY KEY(project_id, section),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
